// generated by ChatGPT
export default class Interval {
  constructor(start, end) {
    this.start = start
    this.end = end
  }

  get length() {
    return Math.abs(this.end - this.start)
  }

  includes(num) {
    return num >= this.start && num <= this.end
  }

  overlaps(other) {
    return this.includes(other.start) || other.includes(this.start)
  }
}
